import Head from 'next/head';
import Image from 'next/image';
import AppLayout from '../components/AppLayout';
import Link from 'next/link';

const style = {
  li: {
    listStyle: 'none',
    padding: '10px',
    fontSize: '1.2rem',
    backgroundColor: '#2a4f79',
    marginBottom: '8px',
    width: '300px',
    textAlign: 'center',
    color: 'white',
    borderRadius: '5px',
  },
};

const PokemonName = ({ data }) => {
  const id = data.url
    .split('/')
    .filter((el) => el != '')
    .pop();

  return (
    <li style={style.li}>
      <Link href={`/pokemones/${id}`}>{data.name.toUpperCase()}</Link>
    </li>
  );
};

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Pokemons</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppLayout>
        <h1>Pokemones</h1>
        <p>Consume la información de todos lo Pokemones</p>
        <ul style={{ padding: '0' }}>
          {data.map((element) => (
            <PokemonName key={element.name} data={element} />
          ))}
        </ul>
      </AppLayout>
    </>
  );
}

export const getStaticProps = async () => {
  const response = await fetch('https://pokeapi.co/api/v2/pokemon?limit=151');
  const data = await response.json();
  return { props: { data: data.results } };
};
